CREATE TABLE host (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL
);
INSERT INTO host (name) VALUES ('Amelia Thompson');
INSERT INTO host (name) VALUES ('Benjamin Martin');
INSERT INTO host (name) VALUES ('Chloe Anderson');
INSERT INTO host (name) VALUES ('David Wilson');
INSERT INTO host (name) VALUES ('Emma Davis');

CREATE TABLE tenant (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL
);
INSERT INTO tenant (name) VALUES ('Json Kowalsky');
INSERT INTO tenant (name) VALUES ('Fiona Garcia');
INSERT INTO tenant (name) VALUES ('George White');
INSERT INTO tenant (name) VALUES ('Holly Taylor');
INSERT INTO tenant (name) VALUES ('Isaac Brown');

CREATE TABLE apartment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  area INTEGER,
  host_id INTEGER NOT NULL,
  price INTEGER,
  description VARCHAR(200)
);
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Oxford Street 123', 45, 2,
120, '3-room apartment with a balcony');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Camden High Street 45', 23, 1,
68, 'studio apartment with a high standard');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Abbey Road 67', 80, 5,
240, 'large 4-room apartment');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Notting Hill Gate 89', 50, 2,
135, '3-room apartment for students');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Baker Street 221B', 58, 2,
155, 'cheap studio apartment in the center');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Fleet Street 34', 70, 3,
205, '4-room fully furnished apartment');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Piccadilly 78', 62, 4,
240, 'high standard apartment with two large rooms');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Portobello Road 56', 35, 1,
120, '2-room apartment for a couple');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Regent Street 10', 120, 3,
450, '5-room luxury apartment');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Tottenham Court Road 123', 90, 5,
315, '4-room pet-friendly apartment');

CREATE TABLE reservation (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  start_of_rental DATE NOT NULL,
  end_of_rental DATE,
  tenant_id INTEGER NOT NULL,
  apartment_id INTEGER NOT NULL,
  cost INTEGER
);
INSERT INTO reservation (start_of_rental, end_of_rental, tenant_id, apartment_id)
VALUES ('2023-03-04', '2023-03-07', 2, 3);

