CREATE TABLE host (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL
);
INSERT INTO host (name) VALUES ('Sophie Hall');
INSERT INTO host (name) VALUES ('Oscar Lee');
INSERT INTO host (name) VALUES ('Ava Scott');
INSERT INTO host (name) VALUES ('Jacob Brown');
INSERT INTO host (name) VALUES ('Olivia Mitchell');

CREATE TABLE tenant (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL
);
INSERT INTO tenant (name) VALUES ('Liam King');
INSERT INTO tenant (name) VALUES ('Isabella Nguyen');
INSERT INTO tenant (name) VALUES ('Lucas Patel');
INSERT INTO tenant (name) VALUES ('Sophia Robinson');

CREATE TABLE apartment (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  area INTEGER,
  host_id INTEGER NOT NULL,
  price INTEGER,
  description VARCHAR(200)
);
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Baker Street 123', 45, 4, 110, '2-room apartment near the park');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Camden Road 67', 23, 4, 60, 'modern studio apartment');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Abbey Gardens 12', 80, 1, 230, 'spacious 4-room apartment');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Notting Hill 56', 50, 5, 120, '3-room apartment for young professionals');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Fleet Street 78', 58, 3, 140, 'cozy studio apartment');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Regent Park 90', 70, 4, 200, 'fully equipped 3-room apartment');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Piccadilly Circus 22', 62, 1, 240, 'luxury 2-room apartment with a view');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Portobello Gardens 10', 35, 2, 85, '1-bedroom apartment for couples');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Tottenham Court 32', 120, 1, 400, 'huge 5-room penthouse');
INSERT INTO apartment (name, area, host_id, price, description) VALUES ('Oxford Circus 89', 90, 3, 300, 'modern 4-room apartment with a terrace');

CREATE TABLE reservation (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) NOT NULL PRIMARY KEY,
  start_of_rental DATE NOT NULL,
  end_of_rental DATE,
  tenant_id INTEGER NOT NULL,
  apartment_id INTEGER NOT NULL,
  cost INTEGER
);
INSERT INTO reservation (start_of_rental, end_of_rental, tenant_id, apartment_id) VALUES ('2023-04-15', '2023-04-20', 1, 5);
INSERT INTO reservation (start_of_rental, end_of_rental, tenant_id, apartment_id) VALUES ('2023-05-18', '2023-05-25', 3, 5);
INSERT INTO reservation (start_of_rental, end_of_rental, tenant_id, apartment_id) VALUES ('2023-06-10', '2023-06-14', 2, 8);
INSERT INTO reservation (start_of_rental, end_of_rental, tenant_id, apartment_id) VALUES ('2023-07-05', '2023-07-12', 4, 2);
INSERT INTO reservation (start_of_rental, end_of_rental, tenant_id, apartment_id) VALUES ('2023-08-01', '2023-08-15', 3, 6);
INSERT INTO reservation (start_of_rental, end_of_rental, tenant_id, apartment_id) VALUES ('2023-10-02', '2023-10-06', 4, 3);
INSERT INTO reservation (start_of_rental, end_of_rental, tenant_id, apartment_id) VALUES ('2023-10-01', '2023-10-05', 1, 6);
INSERT INTO reservation (start_of_rental, end_of_rental, tenant_id, apartment_id) VALUES ('2023-11-10', '2023-11-20', 2, 6);

